Document: starchart
Title: Debian starchart Manual
Author: <insert document author here>
Abstract: This manual describes what starchart is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/starchart/starchart.sgml.gz

Format: postscript
Files: /usr/share/doc/starchart/starchart.ps.gz

Format: text
Files: /usr/share/doc/starchart/starchart.text.gz

Format: HTML
Index: /usr/share/doc/starchart/html/index.html
Files: /usr/share/doc/starchart/html/*.html
